---
# tasks file for postgres
- name: Install Postgres
  ansible.builtin.apt:
      name: "{{ pg_prereq }}"
      state: present
- name: Create postgres database
  become_user: "{{ pg_admin_user }}"
  become: true
  community.postgresql.postgresql_db:
      encoding: "UTF-8"
      name: "{{ pg_dbname }}"

- name: Create user and grant permissions on database.
  become_user: postgres
  become: true
  community.postgresql.postgresql_user:
      db: "{{ pg_dbname }}"
      name: "{{ pg_dbuser }}"
      password: "{{ pg_dbpass }}"
      priv: ALL
      role_attr_flags: SUPERUSER
  no_log: true
